default_language_versions:
  python: python3

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-merge-conflict
      - id: check-yaml
      - id: forbid-new-submodules
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 2.1.4
    hooks:
      - id: markdownlint
      - id: rubocop
  - repo: https://github.com/Lucas-C/pre-commit-hooks-nodejs
    rev: v1.1.1
    hooks:
      - id: dockerfile_lint
  - repo: https://github.com/IamTheFij/docker-pre-commit
    rev: v2.0.0
    hooks:
      - id: hadolint
  - repo: https://github.com/syntaqx/git-hooks
    rev: v0.0.16
    hooks:
      - id: circleci-config-validate
