---
groups:
  - name: master
    jobs:
      - hadolint
      - rubocop
      - rspec
      - shellcheck
      - build-test
      - testinfra
      - docker-build
      - major
      - minor
      - patch

resources:
  - name: resource-git
    type: git
    icon: github
    source:
      uri: https://github.com/Firebladee/docker_test-kitchen.git
      branch: master

  - name: docker-temp
    type: docker-image
    icon: docker
    source:
      repository: ((nexus_ip)):((nexus_docker_port))/testing
      username: ((nexus_username))
      password: ((nexus_password))
      insecure_registries:
        - http://((nexus_ip)):((nexus_docker_port))
        - http://((nexus_ip)):((nexus_docker_group_port))

  - name: docker-build
    type: docker-image
    icon: docker
    source:
      repository: ((nexus_ip)):((nexus_docker_port))/fireblade/test-kitchen
      username: ((nexus_username))
      password: ((nexus_password))
      insecure_registries:
        - http://((nexus_ip)):((nexus_docker_port))
        - http://((nexus_ip)):((nexus_docker_group_port))

  - name: docker-hub
    type: docker-image
    icon: docker
    source:
      repository: fireblade/rspec
      username: ((docker_hub_username))
      password: ((docker_hub_password))

  - name: version
    type: semver
    source:
      driver: git
      uri: git@github.com:Firebladee/docker_test-kitchen.git
      branch: version
      file: version
      initial_version: 0.0.1
      private_key: ((private_key))

jobs:
  - name: hadolint
    public: true
    plan:
      - get: resource-git
        trigger: true
      - task: validate
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: ((nexus_ip)):((nexus_docker_group_port))/hadolint/hadolint
              tag: latest-debian
          inputs:
            - name: resource-git
          run:
            path: sh
            args:
              - -exc
              - |
                hadolint resource-git/Dockerfile

  - name: rubocop
    public: true
    plan:
      - get: resource-git
        trigger: true
      - task: rubocop
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: ((nexus_ip)):((nexus_docker_group_port))/library/ruby
          inputs:
            - name: resource-git
          run:
            path: sh
            args:
              - -exc
              - |
                cd resource-git
                gem install rubocop
                rubocop

  - name: rspec
    public: true
    plan:
      - get: resource-git
        trigger: true
        passed:
          - rubocop
      - task: rspec
        privileged: true
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: ((nexus_ip)):((nexus_docker_group_port))/fireblade/rspec
          inputs:
            - name: resource-git
          run:
            path: sh
            args:
              - -exc
              - |
                source /docker-lib.sh
                start_docker
                cd resource-git
                # rake
        
  - name: shellcheck
    public: true
    plan:
      - get: resource-git
        trigger: true
      - task: shellcheck
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: ((nexus_ip)):((nexus_docker_group_port))/koalaman/shellcheck-alpine
          inputs:
            - name: resource-git
          run:
            path: sh
            args:
              - -exc
              - |
                shellcheck resource-git/*.sh

  - name: build-test
    public: true
    plan:
      - get: resource-git
        passed:
          - hadolint
        trigger: true
      - put: docker-temp
        params:
          build: resource-git
          build_args:
            from: ((nexus_ip)):((nexus_docker_group_port))/library/centos:7

  - name: testinfra
    public: true
    plan:
      - get: resource-git
        passed:
          - shellcheck
          - build-test
          - rspec
        trigger: true
      - task: hello
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: ((nexus_ip)):((nexus_docker_port))/testing
              insecure_registries:
                - http://((nexus_ip)):((nexus_docker_port))
          run:
            path: echo
            args: ["Testinfra"]

  - name: docker-build
    public: true
    plan:
      - get: resource-git
        passed:
          - testinfra
        trigger: true
      - get: version
        params:
          bump: patch
      - put: docker-build
        params:
          build: resource-git
          build_args:
            from: ((nexus_ip)):((nexus_docker_group_port))/library/centos:7
          tag_file: version/version
          tag_as_latest: true
      - put: docker-hub
        params:
          build: resource-git
          build_args:
            from: ((nexus_ip)):((nexus_docker_group_port))/library/centos:7
          tag_file: version/version
          tag_as_latest: true
      - put: version
        params:
          file: version/version

  - name: major
    public: true
    plan:
      - put: version
        params:
          bump: major

  - name: minor
    public: true
    plan:
      - put: version
        params:
          bump: minor

  - name: patch
    public: true
    plan:
      - put: version
        params:
          bump: patch
